// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoS_vcfnjkqEtI3H2lVLNluXnMS8ma4t8',
    appId: '1:670039902105:web:6cdf851a33ec91ad517508',
    messagingSenderId: '670039902105',
    projectId: 'test-cli-e2cc6',
    authDomain: 'test-cli-e2cc6.firebaseapp.com',
    storageBucket: 'test-cli-e2cc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRlOg5qZ1dhoG9x0p7W3V54nLU9m0JYW8',
    appId: '1:670039902105:android:6c301bf7873cac2f517508',
    messagingSenderId: '670039902105',
    projectId: 'test-cli-e2cc6',
    storageBucket: 'test-cli-e2cc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnph1z2Uca0P1dwRTFXvLIO5XMfW0Zt-c',
    appId: '1:670039902105:ios:6b779f7a6be592a1517508',
    messagingSenderId: '670039902105',
    projectId: 'test-cli-e2cc6',
    storageBucket: 'test-cli-e2cc6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnph1z2Uca0P1dwRTFXvLIO5XMfW0Zt-c',
    appId: '1:670039902105:ios:9a545edc605c44e5517508',
    messagingSenderId: '670039902105',
    projectId: 'test-cli-e2cc6',
    storageBucket: 'test-cli-e2cc6.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
